language: node_js
before_script:
  - sudo apt-get update
  - sudo apt-get install libcairo-dev libjpeg-dev
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..

node_js:
  - "0.12"